### PR TITLE
fixed rt sink and source conn to stop thier helpers in terminate. #652 [JIRA: RIAK-1476]

### LINKED ISSUE #649: process leak of rt helper. [JIRA: RIAK-2777]
#### Summary

A customer hit memory leak problem of a sink cluster such that leak memory grows upto 10~20GB at #zd9123. Many riak_repl2_rtsink_helper processes were found in cluster info, which hog ~600MB per a process, and look orphaned.
Unstable network connectivity can cause this because many tcp_error were found in console.log when memory usage were increasing, and I reproduced this problem by simulating them.

You can find whole cluster_info and memory usage graphs at #zd9123. (Most text is in Japanese. sorry.)

In my opinion, to resolve it we should stop riak_repl2_rtsink_helper in riak_repl2_rtsink_conn:terminate/2 but I'm not sure its side effect. According to my test, also riak_repl2_rtsource_helper looks to have same issue in 2.0.4. Both helpers can leak.
##### leaked riak_repl2_rtsink_helper in cluster info

a parent's process looks already gone..

```
=proc:&lt;0.15572.931>
State: Waiting
Spawned as: proc_lib:init_p/5
Spawned by: &lt;0.15571.931>
Started: Sat Dec  6 15:37:53 2014
Message queue length: 0
Number of heap fragments: 0
Heap fragment data: 0
Dictionary: [{'$initial_call',{riak_repl2_rtsink_helper,init,1}},{'$ancestors',[&lt;0.15571.931>,riak_repl2_rtsink_conn_sup,riak_repl2_rtsink_sup,riak_repl2_rt_sup,riak_repl_sup,&lt;0.813.0>]}]
Reductions: 41453917
Stack+heap: 74732575
OldHeap: 0
Heap unused: 20414804
OldHeap unused: 0
Stack dump:
Program counter: 0x00007f900d944460 (gen_server:loop/6 + 264)
CP: 0x0000000000000000 (invalid)
arity = 0
```
##### setup 1 node source cluster (dev1) & 1 node sink cluster (dev2):

To understand the problem easily, we use 1 node cluster on both sides.

```
% git clone riak_ee
% cd riak_ee
% git checkout 2.0
% wget https://gist.githubusercontent.com/ksauzz/cb4bef22621e68f94c2d/raw/6e028f750366643b659291fc09051ef29ccee397/setup_repl_v3_2nodes.sh 
% sh ./setup_repl_v3_2nodes.sh 
```
##### send tcp_error to riak_repl2_rtsink_conn periodically.

simulate unstable network connectivity between source side and sink side.

```
% dev/dev2/bin/riak attach

(dev2@127.0.0.1)1> [begin hd(riak_repl2_rtsink_conn_sup:started())!{tcp_error,<<>>,test}, timer:sleep(2000) end||_<-lists:seq(1,10000)].
```
##### confirm process count at sink side.

```
% while [ true ]; do  curl -s localhost:10028/stats |python -mjson.tool | grep -e sys_proc -e memory_total ; sleep 2; done
    "memory_total": 96117504,
    "sys_process_count": 1916,
    "memory_total": 96140312,
    "sys_process_count": 1917,
    "memory_total": 96119744,
    "sys_process_count": 1918,
    "memory_total": 96121552,
    "sys_process_count": 1919,
    "memory_total": 96144016,
    "sys_process_count": 1920,
    "memory_total": 96111056,
    "sys_process_count": 1921,
    "memory_total": 96101504,
    "sys_process_count": 1922,
    "memory_total": 96124016,
    "sys_process_count": 1923,
```
##### confirm process count at source side.

```
 while [ true ]; do  curl -s localhost:10018/stats |python -mjson.tool | grep -e sys_proc -e memory_total ; sleep 2; done
    "memory_total": 96615264,
    "sys_process_count": 1967,
    "memory_total": 96655880,
    "sys_process_count": 1968,
    "memory_total": 96614616,
    "sys_process_count": 1969,
    "memory_total": 96630664,
    "sys_process_count": 1972,
    "memory_total": 96627296,
    "sys_process_count": 1971,
    "memory_total": 96626688,
    "sys_process_count": 1972,
    "memory_total": 96642608,
    "sys_process_count": 1973,
    "memory_total": 96640680,
    "sys_process_count": 1974,
    "memory_total": 96662136,
    "sys_process_count": 1975,
```

### PR DESCRIPTION
**Pull request by lordnull**
this is intended for 2.0.5. It fixes #649 and allows https://github.com/basho/riak_test/pull/722 to pass.

### CODE REVIEW

File: src/riak_repl2_rtsink_conn.erl [hunk 1]
```diff
@@ -242,8 +242,9 @@ handle_info(report_bt_drops, State=#state{bt_drops = DropDict}) ->
     Report = app_helper:get_env(riak_repl, bucket_type_drop_report_interval, ?DEFAULT_INTERVAL_MILLIS),
     {noreply, State#state{bt_drops = dict:new(), bt_timer = undefined, bt_interval = Report}}.
 
-terminate(_Reason, _State) ->
+terminate(_Reason, State) ->
     %% TODO: Consider trying to do something graceful with poolboy?
+    catch riak_repl2_rtsink_helper:stop(State#state.helper),
```
Comment (jonmeredith) [inline src/riak_repl2_rtsink_conn.erl:247]: Why is this necessary?  The rtsink_helper (and rtsource_helper) are both linked processes.  As soon as the rtsource process terminates the associated helper should die with it.

Comment (kuenishi) [inline src/riak_repl2_rtsink_conn.erl:247]: Normal exit of rtsink_conn is not being trapped by rtsink_helper. Another option is to set `trap_exit` at helpers?

**Comment by kuenishi** [comment]
Just heads up for @jonmeredith ^^;

**Comment by jonmeredith** [comment]
+1 232f1eb

Sorry this languished so long. It's a good change.

File: src/riak_repl2_rtsink_conn.erl (hunk 1 above)
Comment (jonmeredith) [inline src/riak_repl2_rtsink_conn.erl:247]: And the third option to exit with {shutdown, Reason} instead so you can tell why - but I think this terminate option is good for now.

**Comment by Basho-JIRA** [comment]
[~jmeredith] can you review/merge the related riak_test linked in the PR, and shepherd this through to the develop-2.2 branch? Or do we need to assign it to someone else? 

**_[posted via JIRA by Douglas Rohrer]**_

**Comment by Basho-JIRA** [comment]
[~jmeredith]Does this one need to be assigned to someone else, per Doug's comment above?  

**_[posted via JIRA by Patricia Brewer]**_

**Comment by jonmeredith** [comment]
It should be merged and merged forward.

**Comment by Basho-JIRA** [comment]
Did I screw up merging this, or reporting it was merged?

On Thu, Mar 10, 2016 at 6:13 AM Douglas Rohrer (JIRA) <

**_[posted via JIRA by Jon Meredith]**_

**Comment by Basho-JIRA** [comment]
Just didn't see the merge forward, and knew you were busy, so asked Brian to take over. Did you do the forward merge already?

Doug 

**_[posted via JIRA by Douglas Rohrer]**_

**Comment by Basho-JIRA** [comment]
I thought I did - it's easy for Sparrow to double-check - those :stop calls
in the terminate/2 funcs.

On Thu, Mar 10, 2016 at 7:45 AM Douglas Rohrer (JIRA) <

**_[posted via JIRA by Jon Meredith]**_

**Comment by JeetKunDoug** [comment]
resolves #649
